<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="H. Esteban Calisaya Aranda">
<meta name="description" content="Análisis y visualización de encuestas electorales para las Elecciones Generales (Presidencia, Vicepresidencia, Senadurías y Diputaciones) de Bolivia 2025. Explora los datos electorales más recientes, su evolución y algunas posibles explicaciones a los cambios en la intención de voto.">

<title>Elecciones Bolivia 2025 - Encuesta de encuestas: Elecciones Generales Bolivia 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>
<meta name="google-site-verification" content="6TMitLunJmIOOgCVNH0qwU8Jp9Fsmi5UhFKj3PyuvGE">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Elecciones Bolivia 2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#ultima-encuesta" rel="" target="">
 <span class="menu-text">Última encuesta</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#intencion-voto-total" rel="" target="">
 <span class="menu-text">Intención de voto total 2025</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#intencion-voto-valido" rel="" target="">
 <span class="menu-text">Intención de voto válido 2025</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#voto-valido-2025" rel="" target="">
 <span class="menu-text">Voto válido potencial 2025</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#contexto-campana" rel="" target="">
 <span class="menu-text">Contexto campaña electoral 2025</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#voto-oculto-pasado" rel="" target="">
 <span class="menu-text">Voto oculto y precisión elecciones pasadas</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./#voto-oculto-2025" rel="" target="">
 <span class="menu-text">Voto oculto 2025</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/hescalar/encuesta_encuestas_bol25" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#registro-de-cambios" id="toc-registro-de-cambios" class="nav-link active" data-scroll-target="#registro-de-cambios">Registro de cambios</a></li>
  <li><a href="#presentación" id="toc-presentación" class="nav-link" data-scroll-target="#presentación">Presentación</a></li>
  <li><a href="#intención-de-voto-bolivia-última-encuesta-disponible-y-cuadro-resumen-general" id="toc-intención-de-voto-bolivia-última-encuesta-disponible-y-cuadro-resumen-general" class="nav-link" data-scroll-target="#intención-de-voto-bolivia-última-encuesta-disponible-y-cuadro-resumen-general">Intención de voto Bolivia: Última encuesta disponible y cuadro resumen general</a></li>
  <li><a href="#gráficos-de-intención-de-voto-total" id="toc-gráficos-de-intención-de-voto-total" class="nav-link" data-scroll-target="#gráficos-de-intención-de-voto-total">Gráficos de intención de voto total</a>
  <ul class="collapse">
  <li><a href="#el-voto-oculto-no-declarado-y-los-indecisos-en-la-campaña-2025" id="toc-el-voto-oculto-no-declarado-y-los-indecisos-en-la-campaña-2025" class="nav-link" data-scroll-target="#el-voto-oculto-no-declarado-y-los-indecisos-en-la-campaña-2025">El voto oculto / no declarado y los indecisos en la campaña 2025</a></li>
  </ul></li>
  <li><a href="#gráficos-de-intención-de-votos-válidos" id="toc-gráficos-de-intención-de-votos-válidos" class="nav-link" data-scroll-target="#gráficos-de-intención-de-votos-válidos">Gráficos de intención de votos válidos</a></li>
  <li><a href="#voto-oculto-y-precisión-de-las-encuestas-en-las-últimas-elecciones" id="toc-voto-oculto-y-precisión-de-las-encuestas-en-las-últimas-elecciones" class="nav-link" data-scroll-target="#voto-oculto-y-precisión-de-las-encuestas-en-las-últimas-elecciones">Voto oculto y precisión de las encuestas en las últimas elecciones</a>
  <ul class="collapse">
  <li><a href="#las-encuestas-en-la-elección-de-2019" id="toc-las-encuestas-en-la-elección-de-2019" class="nav-link" data-scroll-target="#las-encuestas-en-la-elección-de-2019">Las encuestas en la elección de 2019</a></li>
  <li><a href="#el-regreso-del-mas-ipsp-la-elección-de-2020" id="toc-el-regreso-del-mas-ipsp-la-elección-de-2020" class="nav-link" data-scroll-target="#el-regreso-del-mas-ipsp-la-elección-de-2020">El regreso del MAS-IPSP: la elección de 2020</a></li>
  <li><a href="#estimación-del-voto-oculto" id="toc-estimación-del-voto-oculto" class="nav-link" data-scroll-target="#estimación-del-voto-oculto">Estimación del voto oculto</a></li>
  </ul></li>
  <li><a href="#qué-se-puede-esperar-del-voto-oculto-para-las-elecciones-de-2025" id="toc-qué-se-puede-esperar-del-voto-oculto-para-las-elecciones-de-2025" class="nav-link" data-scroll-target="#qué-se-puede-esperar-del-voto-oculto-para-las-elecciones-de-2025">¿Qué se puede esperar del voto oculto para las elecciones de 2025?</a></li>
  <li><a href="#agradecimientos" id="toc-agradecimientos" class="nav-link" data-scroll-target="#agradecimientos">Agradecimientos</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Encuesta de encuestas: Elecciones Generales Bolivia 2025</h1>
<p class="subtitle lead">Última actualización: 17 de julio de 2025</p>
</div>

<div>
  <div class="description">
    Análisis y visualización de encuestas electorales para las Elecciones Generales (Presidencia, Vicepresidencia, Senadurías y Diputaciones) de Bolivia 2025. Explora los datos electorales más recientes, su evolución y algunas posibles explicaciones a los cambios en la intención de voto.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>H. Esteban Calisaya Aranda </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">27 de junio de 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="registro-de-cambios" class="level2">
<h2 class="anchored" data-anchor-id="registro-de-cambios">Registro de cambios</h2>
<p><strong>17/07/2025:</strong> Se agrega la tabla resumen general de encuestas, se renombra la primera sección a “, se re-escribe la descripción de tendencias en función de las últimas dos encuestas.</p>
<p><strong>16/07/2025:</strong> Se añaden tres nuevas secciones: una sobre el voto oculto histórico y la precisión histórica de las encuestadoras tomando como referencia las elecciones de 2019 y 2020; otra sobre prospectiva del voto oculto en estas elecciones; y una de agradecimientos. Se añaden los datos de la última encuesta de SPIE publicada por El Deber el día de hoy, queda pendiente la reinterpretación a la luz de los últimos datos. Modificaciones estéticas menores. ¡Felicidades La Paz! :)</p>
<p><strong>14/07/2025</strong>: Se introducen algunas ideas a la luz de los datos arrojados por la última encuesta de IPSOS CIESMORI. Se actualiza la presentación.</p>
<p><strong>13/07/2025</strong>: Se añaden los datos de la última encuesta de IPSOS CIESMORI publicada por UNITEL el 13 de julio de 2025. Se optimiza el código para mostrar los promedios de campaña en función de la encuesta más reciente de cada consultora o empresa encuestadora (i.e.&nbsp;IPSOS CIESMORI es la única empresa que cuenta con dos encuestas durante el periodo de campaña, el cálculo de los promedio se hace con la intención de voto de su encuesta publicada hoy, es decir, el más reciente). Se añade nueva sección con los valores de intención de voto de la encuesta más reciente. Dado que NGP se ha retirado de la carrera electoral sus valores quedarán como perdidos de ahora en adelante. Se añaden rectas verticales marcando algunos hitos como el inicio de campaña, el primer debate y la inhabilitación de Jaime Dunn.</p>
<p><strong>02/07/2025</strong>: Ante la inhabilitación de Jaime Dunn se cambia la etiqueta de candidato de NGP a Fidel Tapia Zambrana. La salida de Antonio Saravia también deja como el único candidato visible a Pavel Aracena por LyP-ADN. Modificaciones estéticas en gráficas de intención de voto para que den cuenta de la fecha del fin del levantamiento de las encuestas, se agrupó mayo y junio para gráficas de intención voto desde el inicio de campaña.</p>
<p><strong>01/07/2025</strong>: Añadidas etiqueta de datos sobre barras promedio en gráficas de intención voto total e intención voto válido.</p>
<p><strong>30/06/2025</strong>: Se añade información de la segunda encuesta de Captura Consulting publicada por Red Uno y RTP publicada en esta fecha. También se agrega la primera encuesta de la misma consultora, que corresponde al periodo de fines de marzo. Se introducen algunas modificaciones menores al análisis e interpretación en función de la nueva información. Optimizaciones, cambios estéticos menores en gráficas y correción ortográfica y de estilo del texto.</p>
<p><strong>27/06/2025</strong>: Primera publicación con las encuestas de junio (UNITEL y El Deber) y encuesta de Marcelo Claure de fines de marzo como punto de referencia.</p>
</section>
<section id="presentación" class="level2">
<h2 class="anchored" data-anchor-id="presentación">Presentación</h2>
<p>Este es un ejercicio de análisis electoral y visualización de datos inspirado en el trabajo de <a href="https://polls.politico.mx/">Político.mx</a>, la idea es recopilar en una base de datos públicas las encuestas oficiales (y tal vez las no oficiales) para compararlas en el tiempo. La base de datos se encuentra en este <a href="https://docs.google.com/spreadsheets/d/1Nr5mlVI1PAIXpaOtmRugJbwyriQYlAUt5Ldehq8VZ6E/edit?gid=0#gid=0">archivo de sheets</a> y el diccionario de datos en este <a href="https://docs.google.com/spreadsheets/d/1VJZkKd5dDWnHzbOO3G4o7yeW8jh1GZJIhykaApI05MQ/edit?gid=1761737635#gid=1761737635">otro</a></p>
<p>Si quieres saber quién soy yo, puedes consultar mi linkedIn <a href="https://www.linkedin.com/in/hescalar/">aquí</a>.</p>
<p>Se ha buscado cubrir la mayor cantidad de información disponible y que sea mínimamente comparable. En este sentido, se han incluido dos encuestas no “oficiales”, es decir, que no se encontraban autorizadas ni fueron fiscalizadas por el Tribunal Supremo Electoral TSE al momento de su realización -pues todavía no había necesidad de ello, según los tiempos electorales marcados por el calendario electoral del TSE. Me refiero a la “súper encuesta” de Marcelo Claure y la consultora “panterra.global” y a la primera encuesta que realizó Captura Consulting para Red UNO y RTP. Ambas operaciones estadísticas corresponden al periodo de marzo del presente año y no reflejaban exactamente los mismos candidatos pero sí casi todas las fuerzas políticas (i.e.&nbsp;el contendiente del MAS era Lucho Arce y el de PDC era Chi Hyun Chung y no Rodrigo Paz); de todas maneras, los tres candidatos que ocupaban los tres primeros lugares sí con comparables.</p>
<p>Si bien hay sondeos de opinión todavía más antiguos, partir de tres meses atrás parece ser un buen punto de referencia para observar y explicar algunos cambios recientes en las tendencias. Sin embargo, espero que las encuestas a publicarse en el futuro puedan brindar una base sólida para emprender análisis con mayor potencia estadística y mayor complejidad en la reflexión.</p>
<p>Las tareas pendientes identificadas son:</p>
<ol type="1">
<li><p>Análisis del comportamiento del voto oculto/indecisos. (HECHO)</p></li>
<li><p>Análisis histórico de la precisión de las encuestadoras en elecciones pasadas. (HECHO)</p></li>
<li><p>Análisis histórico del voto rural y su subestimación en las encuestas.</p></li>
<li><p>Breve revisión del padrón electoral.</p></li>
</ol>
</section>
<section id="intención-de-voto-bolivia-última-encuesta-disponible-y-cuadro-resumen-general" class="level2">
<h2 class="anchored" data-anchor-id="intención-de-voto-bolivia-última-encuesta-disponible-y-cuadro-resumen-general">Intención de voto Bolivia: Última encuesta disponible y cuadro resumen general</h2>
<p>Fecha de publicación: 16 de julio</p>
<p>Consultora o empresa encuestadora: SPIE Consulting S.R.L.</p>
<p>Medio de publicación: El Deber</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-ultimaencuesta-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>El siguiente cuadro recoge todas las encuestas, el promedio de votación se calcula desde el inicio oficial de campaña y con el último dato disponible de cada empresa o consultora, es decir, en el caso de SPIE Consulting e IPSOS CIESMORI, dado que ambas tienen dos estudios a la fecha, se usa solamente el dato con el levantamiento más reciente.</p>
<div class="cell">
<div class="cell-output-display">

<div id="psmahluilr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#psmahluilr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#psmahluilr thead, #psmahluilr tbody, #psmahluilr tfoot, #psmahluilr tr, #psmahluilr td, #psmahluilr th {
  border-style: none;
}

#psmahluilr p {
  margin: 0;
  padding: 0;
}

#psmahluilr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 70%;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#psmahluilr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#psmahluilr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#psmahluilr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#psmahluilr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#psmahluilr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#psmahluilr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#psmahluilr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#psmahluilr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#psmahluilr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#psmahluilr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#psmahluilr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#psmahluilr .gt_spanner_row {
  border-bottom-style: hidden;
}

#psmahluilr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#psmahluilr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#psmahluilr .gt_from_md > :first-child {
  margin-top: 0;
}

#psmahluilr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#psmahluilr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#psmahluilr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#psmahluilr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#psmahluilr .gt_row_group_first td {
  border-top-width: 2px;
}

#psmahluilr .gt_row_group_first th {
  border-top-width: 2px;
}

#psmahluilr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#psmahluilr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#psmahluilr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#psmahluilr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#psmahluilr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#psmahluilr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#psmahluilr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#psmahluilr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#psmahluilr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#psmahluilr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#psmahluilr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#psmahluilr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#psmahluilr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#psmahluilr .gt_left {
  text-align: left;
}

#psmahluilr .gt_center {
  text-align: center;
}

#psmahluilr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#psmahluilr .gt_font_normal {
  font-weight: normal;
}

#psmahluilr .gt_font_bold {
  font-weight: bold;
}

#psmahluilr .gt_font_italic {
  font-style: italic;
}

#psmahluilr .gt_super {
  font-size: 65%;
}

#psmahluilr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#psmahluilr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#psmahluilr .gt_indent_1 {
  text-indent: 5px;
}

#psmahluilr .gt_indent_2 {
  text-indent: 10px;
}

#psmahluilr .gt_indent_3 {
  text-indent: 15px;
}

#psmahluilr .gt_indent_4 {
  text-indent: 20px;
}

#psmahluilr .gt_indent_5 {
  text-indent: 25px;
}

#psmahluilr .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#psmahluilr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="9" class="gt_heading gt_title gt_font_normal" style="">Marzo - julio 2025: cuadro resumen encuestas de intención de voto</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="9" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="">Los promedios se calculan desde el inicio de campaña (19-05-2025) en adelante y con el dato de la encuesta más reciente de cada consultora</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="candidat"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a1-.-Captura-Consulting-S.R.L.">1 .  Captura Consulting S.R.L.</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a2-.-panterra.global">2 .  panterra.global</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a3-.-SPIE-Consulting-S.R.L.">3 .  SPIE Consulting S.R.L.</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a4-.-IPSOS-CIESMORI">4 .  IPSOS CIESMORI</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a5-.-Captura-Consulting-S.R.L.">5 .  Captura Consulting S.R.L.</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a6-.-IPSOS-CIESMORI">6 .  IPSOS CIESMORI</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="a7-.-SPIE-Consulting-S.R.L.">7 .  SPIE Consulting S.R.L.</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Promedio-campaña">Promedio campaña</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="candidat" class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">Fecha levantamiento</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">23/03/2025</td>
<td headers="2 .  panterra.global" class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">23/03/2025</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">14/06/2025</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">26/05/2025</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">20/06/2025</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">07/07/2025</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center" style="font-weight: bold; background-color: #F5F5F5;">10/07/2025</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="font-weight: bold; background-color: #F0F0F0;">--</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Samuel Doria Medina</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">17.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">16.0%</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">24.0%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">19.1%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">19.6%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">18.7%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">21.8%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">20.0%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Tuto Quiroga</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">16.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">15.0%</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">22.1%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">18.4%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">16.6%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">18.1%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">20.7%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">18.5%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Andrónico Rodríguez</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">18.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">25.0%</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">14.7%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">14.2%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">13.7%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">11.8%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">8.3%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">11.3%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Manfred Reyes Villa</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">13.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">11.0%</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">9.4%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">7.9%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">8.8%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">8.2%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">10.0%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">9.0%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Rodrigo Paz</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">11.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">13.0%</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">5.6%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">4.3%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">6.4%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">3.2%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">4.0%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">4.5%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Jhonny Fernández</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">--</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">2.6%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">3.7%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">3.8%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">2.5%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">2.4%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">2.9%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Fidel Tapia Zambrana</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">--</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">0.6%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">1.0%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">0.7%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">2.4%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">4.8%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">2.6%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Eduardo Del Castillo</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">1.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">1.7%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">2.3%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">1.4%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">2.3%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">1.9%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">1.9%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Eva Copa</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">--</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">1.4%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">1.7%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">1.1%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">0.6%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">1.1%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">0.9%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Pavel Aracena</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">--</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">0.6%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">0.5%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">--</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">0.2%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">0.4%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">0.3%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Indecisos</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">14.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">20.0%</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">3.0%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">10.0%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">15.5%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">11.3%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">5.3%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">10.7%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Blancos</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">4.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">9.8%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">6.5%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">5.0%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">8.2%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">14.8%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">9.3%</td></tr>
    <tr><td headers="candidat" class="gt_row gt_center">Nulos</td>
<td headers="1 .  Captura Consulting S.R.L." class="gt_row gt_center">6.0%</td>
<td headers="2 .  panterra.global" class="gt_row gt_center">--</td>
<td headers="3 .  SPIE Consulting S.R.L." class="gt_row gt_center">4.5%</td>
<td headers="4 .  IPSOS CIESMORI" class="gt_row gt_center">10.5%</td>
<td headers="5 .  Captura Consulting S.R.L." class="gt_row gt_center">7.4%</td>
<td headers="6 .  IPSOS CIESMORI" class="gt_row gt_center">12.5%</td>
<td headers="7 .  SPIE Consulting S.R.L." class="gt_row gt_center">4.5%</td>
<td headers="Promedio campaña" class="gt_row gt_center" style="background-color: #F0F0F0;">8.1%</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</section>
<section id="gráficos-de-intención-de-voto-total" class="level2">
<h2 class="anchored" data-anchor-id="gráficos-de-intención-de-voto-total">Gráficos de intención de voto total</h2>
<p>La intención de voto total toma en cuenta a los votos blancos, nulos e indecisos, estos tres representan ahora mismo entre 17 y 28 puntos porcentuales. Para referencia, en la elección de 2020 los blancos y nulos alcanzaron apenas 5% de los votos emitidos, en el proceso electoral de 2019 su proporción fue similar, mientras que en las elecciones generales de 2014 estuvieron cerca del 5.8%.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-total1-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Los últimos datos de las encuestadoras muestran un escenario electoral marcado por la volatilidad y altos niveles de indecisión. A tres meses de las elecciones, estos son los hallazgos principales:</p>
<ol type="1">
<li>Competencia cerrada en la punta Samuel Doria Medina (UNIDAD) mantiene una ligera ventaja con un promedio del 20.0% en las encuestas de campaña, seguido de cerca por Tuto Quiroga (LIBRE) con 18.5%. Sin embargo, la última encuesta de SPIE Consulting (10/07) muestra que esta diferencia se ha reducido a apenas 1.1 puntos (21.8% vs 20.7%), dentro del margen de error estadístico.</li>
</ol>
<p>Las variaciones entre encuestadoras son significativas:</p>
<pre><code>SPIE Consulting otorga a Samuel 24.0% en junio y 21.8% en julio

IPSOS CIESMORI lo ubica en 19.1% (mayo) y 18.7% (julio)

Captura Consulting lo sitúa en 19.6% (junio)</code></pre>
<ol start="2" type="1">
<li><p>Caída acelerada de Andrónico Rodríguez El candidato de Alianza Popular ha experimentado un descenso constante:</p>
<p>De 25.0% en marzo (panterra.global) a 8.3% en julio (SPIE)</p>
<p>Promedio durante campaña: 11.3% Su ausencia en el debate presidencial y la división del voto masista parecen factores clave en este retroceso.</p></li>
<li><p>Alto porcentaje de votos no definidos La suma de blancos, nulos e indecisos alcanza en promedio:</p>
<p>28.1% (10.7% + 9.3% + 8.1%) Esta cifra supera ampliamente el 5% histórico y muestra un electorado significativamente descontento o indeciso.</p></li>
<li><p>Otras candidaturas</p>
<p>Manfred Reyes Villa se mantiene estable alrededor del 9.0%</p>
<p>Eduardo del Castillo (MAS-IPSP) no logra despegar (1.9%)</p>
<p>Las demás candidaturas no superan individualmente el 5%</p></li>
</ol>
<p>Factores a considerar:</p>
<pre><code>Discrepancias metodológicas: Las diferencias entre encuestadoras (ej: SPIE vs IPSOS) sugieren cautela al interpretar los datos

Voto rural: Las limitaciones en cobertura de áreas dispersas podrían afectar la precisión

Eventos recientes: El debate presidencial y las inhabilitaciones aún no reflejan todo su impacto</code></pre>
<p>Proyección actual: Si las elecciones fueran hoy, lo más probable sería una segunda vuelta entre Samuel Doria Medina y Tuto Quiroga. Sin embargo, el alto porcentaje de votos no definidos (28.1%) mantiene abierta la posibilidad de cambios significativos en las preferencias.</p>
<p>Nota: Este análisis se basa en las encuestas más recientes de cada consultora, considerando sus respectivos márgenes de error y períodos de levantamiento.</p>
<section id="el-voto-oculto-no-declarado-y-los-indecisos-en-la-campaña-2025" class="level3">
<h3 class="anchored" data-anchor-id="el-voto-oculto-no-declarado-y-los-indecisos-en-la-campaña-2025">El voto oculto / no declarado y los indecisos en la campaña 2025</h3>
<p>Las mayores variaciones entre las encuestas se concentran precisamente en los votos blancos, nulos e indecisos, lo que refleja la volatilidad de este segmento. Para estimar el porcentaje de electores indecisos que emitirán un voto válido, podemos realizar el siguiente cálculo:</p>
<ol type="1">
<li><p><strong>Promedio de indecisos en encuestas recientes</strong>:<br>
<span class="math display">\[
\text{Promedio}_{\text{indecisos, blancos y nulos}} = \frac{25\%\,(\text{SPIE}) + 33\%\,(\text{IPSOS}) + 28\%\,(\text{Captura})}{3} = 28.5\%
\]</span></p></li>
<li><p><strong>Ajuste por votos nulos/blancos históricos</strong>:<br>
Asumiendo que, en etapas finales, alrededor del 5% de los votos serán nulos o blancos (basado en tendencias históricas), el porcentaje estimado de electores indecisos con voto válido sería:<br>
<span class="math display">\[
\text{Indecisos}_{\text{válidos}} = \text{Promedio}_{\text{indecisos, blancos y nulos}} - 5\% = \mathbf{23.5\%}
\]</span></p></li>
</ol>
<p>Por lo tanto, aproximadamente <strong>23.5% del electorado</strong> emitirá un voto válido pero aún no se ha definido por ninguna candidatura. En un contexto de crisis, es probable que esta decisión se retrase hasta el último momento, a menos que un evento catalizador permita a los votantes inclinarse por una opción o descartar alternativas.</p>
<p>Cabe destacar que los hallazgos de todas las encuestadoras muestran cierto grado de consistencia. Todas coinciden en las candidaturas que ocupan el primero, segundo y tercer lugar. Eso sí, las mayores diferencias estadísticamente significativas, es decir, tomando en cuenta los márgenes de error, se dan en la separación porcentual entre los candidatos, como se explica a continuación.</p>
<p>Llama la atención las estimaciones para la candidatura de UNIDAD (Samuel Doria Medina), a quien SPIE Consulting sitúa en el primer lugar con cerca del 25%, mientras que IPSOS CIESMORI también declara ganador a Samuel, pero lo hace con 5% menos, y con una diferencia casi nula con el segundo lugar, ocupado por Tuto Quiroga (LIBRE). Captura Consulting muestra las mismas tendencias, pero con márgenes todavía más modestos, Samuel sería el ganador con 19.6%, seguido por Tuto Quiroga con 16.6% puntos porcentuales menos; esta diferencia de Captura Consulting comparada con las otras encuestas se explica porque también recoge los niveles de indecisión más altos con 15.5%, al igual que nulos y blancos (12.4% si sumamos estos últimos).</p>
<p>Si hablamos de las diferencias entre los primeros y segundos lugares, estas no son estadísticamente significativas en ningún caso. El tercer lugar lo ocupa Andrónico Rodríguez (Alianza Popular). Según IPSOS CIESMORI, el presidente del senado se encuentra relativamente cerca de Tuto -alrededor de 4.2 puntos y a casi 5 puntos de Samuel, pero SPIE Consulting lo posiciona a más de 7 puntos del segundo lugar y casi 10 puntos del primero; Captura Consulting pone a Rodríguez a 3 puntos del segundo lugar y 5 puntos del primero. Este margen relativamente amplio y por encima de los errores estadísiticos proyectados puede ser síntoma de que alguna de las consultoras está errada en la distancia entre Rodríguez y el segundo y primer lugar, o de que hay diferencias cualitativas entre el electorado explicados por los cambios en la coyuntura correspondiente los periodos de levantamiento.</p>
<p>Sobre esto último, IPSOS-CIESMORI realizó su investigación de campo durante la última semana de mayo, SPIE Consulting la llevó a cabo la segunda semana de junio, y Captura Consulting también realizó sus entrevistas durante mediados de junio. Dado que los resultados de IPSOS y Captura muestran mayor consistencia -a pesar de tener 2 semanas entre un operativo estadístico y otro-, parece más probable que las diferencias entre los tres primeros lugares son más pequeñas de lo que a SPIE Consulting (y su medio de comunicación contratante, El Deber) le gustaría.</p>
<p>Teniendo en cuenta que las candidaturas con las campañas aparentemente más organizadas y con más recursos hasta el momento (Samuel y Tuto) son las que están liderando la intención de voto durante el mes de junio, parece ser que el electorado premia a quienes están haciendo su tarea como candidatos. Tal vez la excepción a la regla es Manfred Reyes Villa, quien a pesar de estar movilizando aparato, recursos y visitando medios de comunicación constantemente, parece no poder proyectarse a nivel nacional. Posteriormente (y en función de mi tiempo disponible) intentaré desagregar el análisis al menos a nivel regional, pues las encuestas observadas presentan errores de estimación muy altos a nivel subnacional, en especial en los departamentos menos poblados.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-total2-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Sobra decir que la inestabilidad política, la improvisación de los partidos políticos, la judicialización de la elección y la endeble respuesta del Tribunal Supremo Electoral no han permitido que las campañas despeguen. Muchos de los partidos iniciaron oficialmente sus campañas el fin de semana del 28 de junio. Según el calendario electoral, los partidos pueden presentar sustitutos hasta 45 días antes de la elección en caso de que los candidatos renuncien, esto es, hasta el viernes 4 de julio. En otras palabras, no será hasta esa fecha que se cierren las negociaciones políticas y podamos conocer a las candidaturas “firmes”. Después de ese día, las únicas sustituciones de candidaturas podrán ser por causa de inhabilitación, fallecimiento o incapacidad total. En este sentido, los dos hechos reciente más importante fueron la inhabilitación de Jaime Dunn, el 9 de julio, incluyendo su eliminación de la papeleta; y la negativa definitiva del TSE a la candidatura de Evo Morales con motivo de no haber sido inscrito por ninguna sigla habilitada para estos comicios.</p>
<p>Justamente entrando en la dinámica, es estrepitosa la caída de casi 10 puntos que sufre Andrónico entre fines de marzo y mediados de junio. Mucho ha sucedido en todo este tiempo, el conflicto entre los grupos evistas y el gobierno, su constante inacción ante los embates de sus adversarios (internos y externos) y la escisión definitiva del MAS en tres bloques (el MAS-IPSP como tal, el mismo Andrónico y el grupo evista) parecen haber cobrado una dolorosa factura. Sin embargo, considero también que resulta en el candidato más conciliador y con mayor potencial de crecimiento desde el movimiento popular. Eduardo del Castillo le está representando al MAS-IPSP el nivel de preferencia electoral más bajo en casi 25 años, no me animo a decir si el rechazo se debe a su persona como tal o más bien a que el electorado sigue viendo en él la sombra de Lucho Arce, quién se encuentra en mínimos históricos de aprobación. Y claro, es muy difícil que uno de los ministros más visibles del oficialismo logre desvincular su imagen de la del gobierno arcista a unos meses de las elecciones, por mucho que lo haya estado intentando. Junto el MAS-IPSP se ven 3 candidaturas más que, estadísticamente hablando podrían tener votaciones prácticamente nulas, Eva Copa (MORENA), Antonio Saravia (Libertad y Progreso) y Jaime Dunn (Nueva Generación Patriótica) - en caso de que este último siquiera llegue a ser habilitado.</p>
<p>Parece ser que, aquellos ultra-libertarios que en sus sueños más guajiros pensaron que era posible un Milei boliviano, van a amanecer mojados. La inhabilitación de Dunn y la renuncia de Antonio Saravia confirman lo dicho.</p>
<p>Esto no quita que, y en función de lo que todas las candidaturas han manifestado, sin importar quien gane la elección, el ajuste económico y los correspondientes costos sociales para las clases más vulnerables serán inevitables, pero ese es tema de otro tipo de análisis.</p>
<p>Tomando en cuenta la última información del mes de julio, en función de los datos de la segunda encuesta de IPSOS CIESMORI, la diferencia entre Samuel Doria Medina (primero) y Tuto Quiroga (segundo) es cada vez más cerrada (apenas 0.6%), mientras que la intención de voto de Andrónico Rodríguez sigue cayendo, alcanzando apenas un 11.8%. Esta encuesta fue levantada casi inmediatamente después del primer gran debate presidencial organizado por la Red UNO, en el que participaron Samuel Doria Medina, Tuto Quiroga, Johnny Fernández Manfred Reyes Villa y Eduardo del Castillo. Podría ser que la ausencia de Andrónico Rodríguez en dicho evento haya jugado en contra, sin embargo, si vemos cómo se mueve la votación parece más probable que los puntos que perdió Rodríguez hayan ido a parar al voto indeciso, nulo y blanco, puesto que Tuto y Samuel también han perdido votación, aunque en menor medida.</p>
<p>Lo observado parece ser síntoma de que <strong>el primer debate de los candidatos de cara al país generó más dudas que certezas</strong>. Tampoco puede menospreciarse el papel del ala evista del masismo histórico (hoy en la inhabilitada sigla PAN-BOL) y su máximo líder, Evo Morales Ayma, quienes han llamado expresamente al voto nulo, negando así su bendición a Rodríguez, a pesar de que este resultaría el actor más cercano al evismo de todas las candidaturas que aparecen en la papeleta electoral.</p>
<p>Tampoco pueden subestimarse tres elementos:</p>
<ol type="1">
<li><p>El voto oculto que ha acompañado al masismo en las últimas 2 elecciones y que terminó dando la sorpresa en los comicios de 2019 y 2020.</p></li>
<li><p>Los altos márgenes de error de las encuestas desagregadas a nivel departamental, que en La Paz son de 5.4%, Cochabamba 5.5% y Santa Cruz 5.4%, dado que estos departamentos representan al 73.5% del padrón electoral.</p></li>
<li><p>La subestimación del voto en el área rural para la encuesta de IPSOS CIESMORI a principios de julio, pues dado el contexto geográfico y un operativo de campo tan corto, resulta cuando menos improbable que se haya cubierto el área dispersa con un muestreo adecuado.</p></li>
</ol>
</section>
</section>
<section id="gráficos-de-intención-de-votos-válidos" class="level2">
<h2 class="anchored" data-anchor-id="gráficos-de-intención-de-votos-válidos">Gráficos de intención de votos válidos</h2>
<p>Finalmente, se presenta el ejercicio con el voto efectivo, aunque este debe ser tomado con precaución, dado el altísimo porcentaje de indecisos, nulos y blancos, que pueden fluctuar mucho entre hoy y el día de la elección.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-efectivo1-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Las tendencias siguen el mismo camino de la votación total, el único objetivo de estas visualizaciones es observar si alguna candidatura se acerca al ansiado 50% + 1 voto que permite una victoria en primera vuelta. Sin embargo para el mes de junio, ninguno alcanza siquiera el 30% de votos válidos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-efectivo2-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>En la virtual situación de que la elección fuera este fin de semana y que los indecisos no tomen partido alguno, la segunda vuelta sería contendida por Samuel Doria Medina y Tuto Quiroga Ramírez.</p>
</section>
<section id="voto-oculto-y-precisión-de-las-encuestas-en-las-últimas-elecciones" class="level2">
<h2 class="anchored" data-anchor-id="voto-oculto-y-precisión-de-las-encuestas-en-las-últimas-elecciones">Voto oculto y precisión de las encuestas en las últimas elecciones</h2>
<p>Esta sección revisará brevemente el comportamiento del voto oculto y la calidad predictiva de las consultoras comparando las últimas encuestas disponibles previas a las elecciones de 2019 y 2020, respectivamente. No es pretensión de este texto profundizar en la discusión sobre el golpe de estado en 2019, sin embargo, resultará inevitable abordar el asunto al momento de describir las cifras. Es importante señalar que los datos oficiales que se muestran aquí no coinciden con los resultados oficiales reportados por el Tribunal Supremo Electoral en ambas elecciones, esto se debe a que el TSE informa sobre los votos válidos, es decir, excluye los votos nulos y blancos para el cálculo de los porcentajes. Para fines de comparabilidad con los datos de las encuestadoras, se recalcularon las proporciones para que la votación de las candidaturas, blancos y nulos sumen el 100%.</p>
<section id="las-encuestas-en-la-elección-de-2019" class="level3">
<h3 class="anchored" data-anchor-id="las-encuestas-en-la-elección-de-2019">Las encuestas en la elección de 2019</h3>
<p>Si bien fueron cuestionados, el análisis se basa en los resultados electorales oficiales publicados por el Tribunal Supremo Electoral. Al respecto, las encuestas de IPSOS y VIA CIENCIA fueron las más cercanas al resultado oficial reportado por el TSE; para el segundo lugar (Carlos D. Mesa) VIA CIENCIA y la UMSA son las que mostraron las estimaciones más próximas, aunque alejadas. Si observamos los intervalos de confianza, ni una sola de las encuestadoras estuvo próxima a los resultados oficiales de los dos primeros lugares en términos estadísticos.</p>
<p>Si hablamos de los niveles de votos nulos y blancos, IPSOS fue la consultora que mejor estimó estas votaciones, y sus indecisos tendrían que haberse repartido de la siguiente manera, ~9% hacia Comunidad Ciudadana y ~4% hacia el MAS-IPSP, solo así se acercaría al resultado oficial. VIA CIENCIA también muestra una estimación aceptable de nulos y blancos, pero sus niveles de indecisión no cierran cuando se intenta repartirlos entre el primer y segundo lugar. Igualmente, todas las encuestadoras sin excepción sobre-estimaron el cuarto lugar (Oscar Ortíz) y subestimaron al <em>outsider</em> de esta elección, Chi Hyng Chung (PDC), que quedó tercero.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-2019-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Es cuando menos improbable que todas las encuestas estén mal, el muestreo y la estimación estadística son disciplinas cuyo objetivo es dar grados de certeza administrando la incertidumbre de una manera científica -esto se hace calculando los márgenes de error del estudio y su nivel de confianza. No son una ciencia exacta, pero sí manejan parámetros de confiabilidad que, cuando se hacen bien, reflejan el comportamiento de la población que buscan representar, en este caso, la votación. A la luz de esto, “entusiastas” de la tesis del fraude podrían decir que la distorsión vino de la manipulación de la votación a favor del oficialismo. No obstante, de haber sucedido, no tiene sentido que todas las encuestadoras también hayan subestimado por tanto la votación de Carlos D. Mesa (Comunidad Ciudadana), principal opositor de Evo Morales en esas elecciones.</p>
<p>Lo dicho nos reduce a los siguientes escenarios:</p>
<ol type="1">
<li><p>Todas las encuestadoras hicieron un mal diseño muestral (etapa de diseño del estudio), pésimos instrumentos (preguntas mal planteadas o que inducían a ciertas respuestas), un trabajo de campo deficiente (etapa de levantamiento de la información, es decir, personal encuestador poco hábil, que falsea respuestas o una pobre validación) o todas las anteriores. En este caso, los problemas vienen de la capacidad técnica de las empresas. Aquí puede incluirse también la tradicional falencia de las encuestadoras para representar de forma precisa la votación en las áreas rurales, en especial las dispersas, a lo largo del país.</p></li>
<li><p>La población mostró cambios radicales en su intención de voto durante la semana y media previa a la elección.</p></li>
</ol>
<p>Debido a la inexistencia de un evento de importancia (i.e.&nbsp;la revelación del supuesto hijo de Evo con Gabriela Zapata un par de semanas antes del referéndum para la tercera postulación de Morales) que explique el cambio de corazón de las y los electores; y dado que los números tampoco muestran evidencia que permita hablar de una operación armada para tumbar al MAS-IPSP desde lo que reportan las encuestas, todo parece indicar que el escenario más probable es el primero.</p>
<p>Sin embargo centrémonos en la estimación de la diferencia entre el primer y el segundo lugar, recordemos también que aquí no estamos observando la votación válida sino la total, es decir, que cuando se excluyan los votos nulos y blancos, todos los porcentajes crecen, en especial el primer y el segundo lugar:</p>
<table class="table">
<colgroup>
<col style="width: 32%">
<col style="width: 17%">
<col style="width: 27%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Consultora</strong></th>
<th><strong>MAS-IPSP</strong></th>
<th><strong>Comunidad Ciudadana</strong></th>
<th><strong>Diferencia</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Resultados Oficiales TSE</strong></td>
<td><strong>44.7%</strong></td>
<td><strong>34.7%</strong></td>
<td><strong>+10.0%</strong></td>
</tr>
<tr class="even">
<td>IPSOS</td>
<td>40.0%</td>
<td>22.0%</td>
<td><strong>+18.0%</strong></td>
</tr>
<tr class="odd">
<td>VIA CIENCIA</td>
<td>38.8%</td>
<td>28.4%</td>
<td><strong>+10.4%</strong></td>
</tr>
<tr class="even">
<td>CIESMORI</td>
<td>36.2%</td>
<td>26.9%</td>
<td><strong>+9.3%</strong></td>
</tr>
<tr class="odd">
<td>UMSA</td>
<td>32.3%</td>
<td>27.0%</td>
<td><strong>+5.3%</strong></td>
</tr>
</tbody>
</table>
<p>Esto es importante porque un detonante de la crisis política fue la diferencia muy ajustada que permitía la victoria en primera vuelta. Recordemos que la Constitución y la Ley de Régimen Electoral bolivianas indican que la persona que preside el país es elegida en primera vuelta cuando:</p>
<ol type="a">
<li><p>Obtiene el <span class="math inline">\(50\% + 1\)</span> voto de la votación válida.</p></li>
<li><p>Obtiene más del <span class="math inline">\(40\%\)</span> de votación válida con una diferencia de <span class="math inline">\(10\%\)</span> con el segundo lugar.</p></li>
</ol>
<p>Entonces, si tomamos en cuenta el ajuste en los porcentajes por la votación válida, los márgenes de error y los votos indecisos que se estimaron de forma consistente, al menos 3 de 4 consultoras predijeron la victoria del MAS-IPSP con más de 40% de votación y 10% de diferencia con la segunda fuerza política, Comunidad Ciudadana. Por tanto, la tesis del fraude no se sostiene desde el análisis de las encuestas electorales, mientras que el golpe de estado cobra más sentido, mencionaremos un poco más al respecto en la siguiente sección.</p>
<p>Finalmente, si se hiciera una evaluación de qué consultoras fueron las menos imprecisas, IPSOS y VIA CIENCIA estiman los valores más parecidos al resultado oficial del primer lugar, y los blancos/nulos. Además, captan adecuadamente la diferencia entre el primero y el segundo. CIESMORI también representa bien esta diferencia, aunque subestima el primer y segundo lugar por casi 10 puntos.</p>
</section>
<section id="el-regreso-del-mas-ipsp-la-elección-de-2020" class="level3">
<h3 class="anchored" data-anchor-id="el-regreso-del-mas-ipsp-la-elección-de-2020">El regreso del MAS-IPSP: la elección de 2020</h3>
<p>Resulta inevitable dar una descripción coyuntural sintética para hablar de la elección de 2020, trataré aquí de presentar algunas ideas y caracterizaciones en las que existen consensos amplios y, en lo posible, despojadas de juicios de valor.</p>
<p>La movilización de un sector de la población urbana volcada en las calles y la operación política de la dirigencia opositora en octubre y noviembre de 2019 resultaron en la interrupción del mandato constitucional de Evo Morales. El gobierno de Jeanine Añez se gestó de una manera, por decir lo menos, irregular. Pasó de segunda vicepresidenta a presidenta del senado en una sesión convocada por ella misma, sin el quórum suficiente, en la que no se respetó el reglameno de la cámara alta -pues, ante la renuncia de Adriana Salvatierra la presidencia debió recaer en el bloque de mayoría, es decir, el MAS-IPSP, no en su persona. Posteriormente, convocó a una sesión bi-camaral donde anunció que, por sucesión constitucional, asumía como presidenta del país. Trasladándose a Palacio Quemado - ubicado al frente del edificio de la Asamblea Legislativa- unos minutos después, juró como jefa de estado en medio de militares y dirigentes opositores. En este punto, sin importar si existió un fraude electoral o no -pues una irregularidad no es justificación para cometer otra, la forma en que Añez toma la presidencia confirma lo que se ha denominado como “golpe blando”.</p>
<p>Lo señalado y el accionar de su gobierno devinieron en que su gestión esté marcada por:</p>
<ol type="1">
<li><p>La ilegitimidad y la tensión casi constante con el movimiento popular. Pues más allá de si la crisis política devino en un golpe o fue consecuencia de un fraude, Jeanine Añez era una figura desconocida, carente de una base social, legal y política que la respalde más allá de su partido -minoritario en la Asamblea Legislativa.</p></li>
<li><p>Las masacres de Senkata y Sacaba, que inflamaron al movimiento popular, indígena y campesino, y lo arrojaron de regreso al liderazgo de la entonces oposición masista.</p></li>
<li><p>La disrupción ocasionada por la pandemia, los constantes escándalos de corrupción y una respuesta gubernamental cuando menos ineficiente -sino negligente, y que además fue usada como excusa para alargar el mandato de un gobierno cuya única tarea era convocar a una nueva elección.</p></li>
<li><p>El estilo autoritario del entonces Ministro de Gobierno, Arturo Murillo, quien en vez de tender puentes de diálogo con los movimientos sociales, los reprimía, deshumanizaba y criminalizaba.</p></li>
</ol>
<p>En este contexto es que se llega a las elecciones de octubre de 2020, en las que el MAS-IPSP participa en las urnas sin su candidato histórico -pues Evo Morales dio un paso al costado y además se encontraba fuera del país en calidad de refugiado. De esta manera, quién tomó la posta fue su ex Ministro de Economía, Luis Arce Catacora, el único miembro del gabinete que no había sido reemplazado durante los 14 años de gestión -solo estuvo fuera del cargo brevemente para atender una enfermedad en 2017, y que era percibido interna y externamente como el artífice del milagro económico boliviano. Arce también apelaba a un voto de la clase media y era un candidato más fácil de digerir para los sectores urbanos que se habían movilizado en las calles durante el golpe de 2019.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="old_version_files/figure-html/grafico-2020-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Volvamos a los datos, todos vimos como los resultados de la elección sacudieron al mundo, pues todas las predicciones erraron de forma monumental. Si bien 3 de 4 encuestadoras dieron la victoria a la candidatura que efectivamente ganó la elección, lo hicieron con una votación muchísimo menor. Es necesario matizar que durante esa elección también se veían niveles de indecisión elevados, en el orden del 15% en promedio, pero con grandes variaciones según la encuestadora -i.e.&nbsp;para CIESMORI los indecisos nulos y blancos estaban cerca del 28%, mientras que para la UMSA e IPSOS se encontraban en el orden del 21%.</p>
<p>De esta manera, ninguna encuestadora previó una victoria en primera vuelta para el MAS-IPSP -más aún, para Mercados y Muestras la victoria era de Comunidad Ciudadana. De cualquier manera, el escrutinio nacional e internacional casi policial con el que se llevó a cabo el proceso electoral no permitió que se repita la narrativa del fraude que había funcionado en 2019. La diferencia entre Arce y Mesa era demasiado amplia para ponerse en duda. El MAS-IPSP ganó por mucho, pero niguna de las encuestadoras lo vio venir.</p>
<p>IPSOS mostró la estimación puntual más cercana para el primer lugar, aunque quedó cerca de 19% por debajo del resultado oficial, su estimación tampoco muestra diferencias estadísticamente significativas con la UMSA ni CIESMORI. En lo que refiere al segundo lugar, casi todas las encuestadoras estimaron un intervalo de confianza que daba cuenta del resultado final, la excepción fue CIESMORI. Para el tercer lugar sucedió lo mismo que para el segundo.</p>
<p>Ninguna encuestadora estimó votaciones por encima del 40% y menos una diferencia de 10% entre el primero y el segundo, es decir, las encuestas perfilaban una segunda vuelta. En este punto es necesario analizar el comportamiento de los indecisos: IPSOS fue la única encuestadora que estimó bien la votación de nulos, es decir que, entre blancos e indecisos estamos hablando de cerca de 17.2% -esto ajustando por las diferencias entre la estimación puntual de blancos y nulos con los resultados oficiales, y sumándolas a su porcentaje estimado de indecisos. Si comparamos los resultados reales, prácticamente la totalidad de los indecisos reales (indecisos estimados más blancos sobre-estimados más nulos subestimados) tuvo que haber votado por el MAS-IPSP, es decir, que el voto indeciso fue en realidad voto oculto masista.</p>
<p>Hablemos ahora del estudio realizado por la UMSA, que es el que sigue en términos de precisión de sus estimaciones puntuales, emulando el ejercicio anterior su total de indecisos reales fueron alrededor de 16.6%. Para alcanzar el resultado real también es necesario que el total de esos indecisos se sume a la votación del MAS para alcanzar poco más del 50% de votación que obtuvo en los resultados oficiales.</p>
<p>No analizaré los resultados de CIESMORI porque sus estimaciones para el segundo lugar, tercer lugar, blancos y nulos no fueron estadísticamente precisas, pero al menos no erró en las grandes tendencias. No puede decirse lo mismo de la encuesta de Mercados y Muestras, que estimaba un empate técnico con victoria para el segundo lugar. Este es el único estudio completamente inconsistente con todos los demás, además de que sus reportes no diferencian entre blancos e indecisos. En suma, los hallazgos de esta última encuestadora parecen responder a intereses completamente ajenos a un ejercicio estadístico serio.</p>
</section>
<section id="estimación-del-voto-oculto" class="level3">
<h3 class="anchored" data-anchor-id="estimación-del-voto-oculto">Estimación del voto oculto</h3>
<p>Para fines analíticos me planteo estimar el voto oculto de la siguiente manera:</p>
<p><span class="math display">\[\text{Voto oculto} = \text{Indecisos/No Declarados} + |\text{Blancos}_{\text{estimado}} - \text{Blancos}_{\text{oficial}}| + |\text{Nulos}_{\text{estimado}} - \text{Nulos}_{\text{oficial}}|\]</span></p>
<p><strong>Ventajas</strong>:</p>
<ol type="1">
<li><strong>Simple</strong>: Usa datos disponibles en todas las encuestas.</li>
<li><strong>Comparable</strong>: Permite jerarquizar a las consultoras por potencial subestimación o sobre-estimación.</li>
</ol>
<p><strong>Falencias</strong>:</p>
<ol type="1">
<li><strong>Indecisos ≠ ocultos</strong>: Algunos indecisos terminan votando en blanco o nulos.</li>
<li><strong>Asimetría</strong>: No distingue si el error fue sobrestimación o subestimación.</li>
<li><strong>Incertidumbre en su asignación</strong>: No es posible saber con seguridad a qué partido terminaron beneficiando.</li>
</ol>
<p><strong>Idoneidad</strong>:</p>
<ul>
<li><strong>Caso boliviano</strong>: Las encuestas sistemáticamente sobrestiman blancos/nulos, sugiriendo ocultamiento real.</li>
<li><strong>Fines prácticos</strong>: Aunque imperfecta, es un indicador útil para ajustar interpretaciones.</li>
</ul>
<p><strong>Supuestos</strong></p>
<ul>
<li>Las personas encuestadas <strong>no mienten</strong> sobre su intención de voto.</li>
<li>Los votos no declarados terminan siendo <strong>mayoritariamente votos válidos</strong>, no nulos ni blancos.</li>
</ul>
<section id="voto-oculto-en-las-elecciones-2019-y-2020" class="level4">
<h4 class="anchored" data-anchor-id="voto-oculto-en-las-elecciones-2019-y-2020">Voto oculto en las elecciones 2019 y 2020</h4>
<p>En el caso de Bolivia es necesario explicar una condición específica que se dio en 2019. Todo indica que el voto oculto se reparte mayoritariamente entre las dos primeras fuerzas. Si bien es temerario asumir esto, en esa elección las tercera fuerza fuerza política fue subestimada por las encuestas casi en la misma proporción en que la cuarta fue sobre-estimada, y las demás presentan niveles de votación mínimos, por lo que la circulación del de voto oculto tuvo que darse en las candidaturas que muestran mayores variaciones con el resultado oficial, es decir, el MAS-IPSP y Comunidad Ciudadana.</p>
<p>En 2020, el voto de todas las candidaturas, a excepción de la ganadora, fue en general bien estimado, por lo que no hay consideraciones adicionales puesto que el voto oculto irá mayoritariamente a la fuerza política con mayor variación entre sus estimaciones y el resultado oficial, es decir, al MAS-IPSP.</p>
<p>Dicho esto, tenemos dos escenarios</p>
<p><strong><em>Escenario 1. Elecciones 2019</em></strong></p>
<p><em>Características de coyuntura:</em> Niveles de indecisión moderados (en torno a los 10 y 15 puntos porcentuales). Entorno económico sólido. Clima social atemperado pero presto a ebullir. Previa derrota electoral del MAS (21-F). Gobierno previo legítimo, aunque debilitado. Operación política y comunicativa para crear desconfianza en la elección.</p>
<p><em>Estimación del voto oculto:</em></p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Consultora</strong></th>
<th style="text-align: center;"><strong>Indecisos / No Declarados</strong></th>
<th style="text-align: center;"><strong>Δ Blancos</strong></th>
<th style="text-align: center;"><strong>Δ Nulos</strong></th>
<th style="text-align: center;"><strong>Voto oculto</strong></th>
<th style="text-align: center;"><p><strong>MAS-IPSP</strong></p>
<p><strong>(Oficial: 44.7%)</strong></p></th>
<th style="text-align: center;"><p><strong>CC</strong></p>
<p><strong>(Oficial: 34.7%)</strong></p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">IPSOS</td>
<td style="text-align: center;">13%</td>
<td style="text-align: center;">%0.4</td>
<td style="text-align: center;">0.5%</td>
<td style="text-align: center;"><strong>13.9%</strong></td>
<td style="text-align: center;">40.0% (-4.7 pp)</td>
<td style="text-align: center;">22.0% (-12.7 pp)</td>
</tr>
<tr class="even">
<td style="text-align: center;">VIA CIENCIA</td>
<td style="text-align: center;">6.6%</td>
<td style="text-align: center;">%0.1</td>
<td style="text-align: center;">0.9%</td>
<td style="text-align: center;"><strong>7.6%</strong></td>
<td style="text-align: center;">38.8% (-5.9 pp)</td>
<td style="text-align: center;">28.4% (-6.3 pp)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CIESMORI</td>
<td style="text-align: center;">11.3%</td>
<td style="text-align: center;">%4.8</td>
<td style="text-align: center;">1.8%</td>
<td style="text-align: center;"><strong>17.9%</strong></td>
<td style="text-align: center;">36.2% (-8.5 pp)</td>
<td style="text-align: center;">26.9% (-7.8 pp)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Promedio</strong></td>
<td style="text-align: center;"><strong>10.3%</strong></td>
<td style="text-align: center;"><strong>1.8%</strong></td>
<td style="text-align: center;"><strong>1.1%</strong></td>
<td style="text-align: center;"><strong>13.1%</strong></td>
<td style="text-align: center;"><strong>38.3% (-6.4 pp)</strong></td>
<td style="text-align: center;"><strong>25.8% (-8.9 pp)</strong></td>
</tr>
</tbody>
</table>
<p><em>Comportamiento del voto oculto:</em> Expresados en indecisos y sobrestimación/subestimación de blancos y nulos, muestran un comportamiento más o menos equilibrado entre las dos primeras fuerzas, favoreciendo un poco más a la segunda (Comunidad Ciudadana) que a la primera (MAS-IPSP). Los datos indican que el voto oculto fue subestimado por alrededor de 2 puntos porcentuales, es decir, que más allá de los errores, 2.4% de los votos fueron asignados a fuerzas que no eran y en realidad beneficaban al primer y segundo lugar. Además, en promedio, 58% del voto oculto tuvo que ir a Carlos D. Mesa y 42% a Evo Morales.</p>
<p><strong><em>Escenario 2. Elecciones 2020</em></strong></p>
<p><em>Características de coyuntura:</em> Niveles de indecisión altos (entorno al 20%). Entorno económico pauperizado (por la pandemia del COVID-19). Clima social tenso. Previa derrota electoral-institucional del MAS (desconocimiento de la elección previa y golpe blando). Gobierno previo ilegítimo (Añez). Alto grado de confianza en la elección.</p>
<p><em>Estimación del voto oculto:</em></p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Consultora</strong></th>
<th style="text-align: center;"><strong>Indecisos / No Declarados</strong></th>
<th style="text-align: center;"><strong>Δ Blancos</strong></th>
<th style="text-align: center;"><strong>Δ Nulos</strong></th>
<th style="text-align: center;"><strong>Voto oculto</strong></th>
<th style="text-align: center;"><p><strong>MAS-IPSP</strong></p>
<p><strong>(Oficial: 52.3%)</strong></p></th>
<th style="text-align: center;"><p><strong>CC</strong></p>
<p><strong>(Oficial: 27.4%)</strong></p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">UMSA</td>
<td style="text-align: center;">9.9%</td>
<td style="text-align: center;">4%</td>
<td style="text-align: center;">2.7%</td>
<td style="text-align: center;"><strong>16.6%</strong></td>
<td style="text-align: center;">33.6% (-18.7 pp)</td>
<td style="text-align: center;">26.8% (-0.6 pp)</td>
</tr>
<tr class="even">
<td style="text-align: center;">IPSOS</td>
<td style="text-align: center;">10%</td>
<td style="text-align: center;">5.8%</td>
<td style="text-align: center;">1.4%</td>
<td style="text-align: center;"><strong>17.2%</strong></td>
<td style="text-align: center;">34.0% (-18.3 pp)</td>
<td style="text-align: center;">27.9% (+0.5 pp)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CIESMORI</td>
<td style="text-align: center;">21.8%</td>
<td style="text-align: center;">3.4%</td>
<td style="text-align: center;">2.3%</td>
<td style="text-align: center;"><strong>27.5%</strong></td>
<td style="text-align: center;">32.4% (-19.9 pp)</td>
<td style="text-align: center;">24.5% (-2.9 pp)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Promedio</strong></td>
<td style="text-align: center;"><strong>13.9%</strong></td>
<td style="text-align: center;"><strong>4.4%</strong></td>
<td style="text-align: center;"><strong>2.1%</strong></td>
<td style="text-align: center;"><strong>20.4%</strong></td>
<td style="text-align: center;"><strong>33.3% (-19.0 pp)</strong></td>
<td style="text-align: center;"><strong>26.4% (-1.0 pp)</strong></td>
</tr>
</tbody>
</table>
<p><em>Comportamiento del voto oculto:</em> Expresados en indecisos y sobrestimación/subestimación de blancos y nulos. Hay una sobre-estimación mínima del voto oculto (0.4%), el 99.5% del voto oculto terminó en el MAS-IPSP.</p>
</section>
</section>
</section>
<section id="qué-se-puede-esperar-del-voto-oculto-para-las-elecciones-de-2025" class="level2">
<h2 class="anchored" data-anchor-id="qué-se-puede-esperar-del-voto-oculto-para-las-elecciones-de-2025">¿Qué se puede esperar del voto oculto para las elecciones de 2025?</h2>
<p>Hasta el momento las características de la coyuntura actual se corresponden mejor con la elección de 2020. Los niveles de indecisión están sobre el <span class="math inline">\(23\%\)</span>, la crisis económica es la peor en décadas y el clima social pende de un hilo. Es justamente la perspectiva la elección lo que, de alguna manera, contiene un estallido social generalizado; más que gozar de confianza, para la mayoría de las y los bolivianos, la elección es percibida como un medio para salir de la crisis -si esta expectativa es justificada o no es cuestión de otra discusión. El gobierno de Arce se encuentra en mínimos históricos de aprobación, y continuas denuncias por corrupción, por lo que su legitimidad es muy débil.</p>
<p>Sin embargo, sería un grave error pensar que los escenarios de 2020 y el que enfrentamos hoy son intercambiables de forma mecánica. Si bien hay similitudes, existen muchos matices que hacen a esta elección todavía más incierta. La principal que yo percibo se relaciona con la legitimidad de las candidaturas. Las encuestas muestran que los votos no válidos (indecisos, blancos y nulos) van en aumento. En 2020 la población fue a las urnas para sacar al gobierno de Añez, y abrazó al MAS-IPSP -poniendo a un lado los desacuerdos que podía tener con dicho partido- como un símbolo de estabilidad y eficiencia gubernamental que representaba una cotidianidad mejor. Hoy, la crisis económica sume al pueblo boliviano en un <em>deja vú</em> de lo que le pasó en el 85 durante el gobierno de la UDP.</p>
<p>Sumado a esto, la judicialización de la elección y la ausencia de Evo Morales en la papeleta electoral solo deslegitima más el todo el proceso, no hablo aquí de la elección como un mecanismo para nombrar representantes, sino de la democracia misma. Y ese desencanto no solo es observable en los partidarios del evismo, sino en todo el electorado al que todas las candidaturas están siendo incapaces de llegar y convencer.</p>
<p>Si bien a estas alturas es claro que un sector importante del electorado muestra animadversión, no le interesa si Evo es candidato o no lo es, o, simplemente, prefiere que la elección se realice lo antes posible; no es menos cierto que sigue siendo el actor político más importante del país. Basta revisar los medios de comunicación, las declaraciones de la clase política, las entrevistas de los candidatos. Todos sin excepción hablan de Evo, del evismo, de lo que hace o deja de hacer, lo que dice o deja de decir. Guste o no guste, quien sigue marcando la pauta en la política boliviana se encuentra en atrincherado en algún lugar del trópico cochabambino, impedido de participar en la elección.</p>
<p>En mi opinión, esto no significa que la participación de Evo en la elección hubiera significado automáticamente la victoria del masismo. Sin embargo, si la oposición u otras vertientes del MAS-IPSP querían dejar atrás al histórico caudillo, era necesario hacerlo en el campo político, no en el judicial.</p>
<p>Volvamos al tema principal, el comportamiento del voto oculto. Dada la coyuntura actual, si Andrónico Rodríguez logra convencer al electorado de que representa el regreso a la estabilidad de los primeros 14 años del MAS-IPSP, lo más probable es que el voto oculto latente pueda volcarse en buena medida hacia él, pensemos en alrededor de un ~16%. Los últimos datos (16/07/2020) confirman que no lo está logrando, su intención de voto va hacia la baja, su tardío inicio de campaña y propuestas que no resuenan ni emocionan en la gente están sepultando sus oportunidades en esta elección. Pero el desempeño de Andrónico también se explica por un factor adicional, la reticencia de Evo a brindarle su apoyo, o al menos no atacarlo, ni llamar a sus partidarios a votar nulo. Si esta actitud se mantiene, el potencial crecimiento de Andrónico Rodríguez se limita de forma importante, yo creo -y por esta vez, sin otra herramienta que mi intución- que este puede reducirse a la mitad, es decir, que en el contexto actual el voto oculto de Andrónico apenas alcanzaría un ~8%.</p>
<p>No me animo a tratar de entender las razones por las que Evo no está dispuesto a conciliar. Lo que sí puedo decir es que si el pragmatismo político que llame a una unidad del masismo escindido, y otras corrientes progresistas o populares, no prima por encima de las rencillas y diferencias que han fracturado al MAS-IPSP, es altamente probable que la segunda vuelta la disputen dos partidos de derecha.</p>
</section>
<section id="agradecimientos" class="level2">
<h2 class="anchored" data-anchor-id="agradecimientos">Agradecimientos</h2>
<p>Agradezco las revisiones y sugerencias de Shirley Aguilar Miranda, Elvia Chavarría Martínez, Carlos Ernesto Peñaranda Sánchez y Víctor Hugo Calisaya Hinojosa.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>